name: Bootstrap Action

inputs:
  node-version:
    type: string
    required: false
    default: lts/*
  git-ref:
    type: string
    required: false
    default: ''
  git-fetch-depth:
    type: number
    required: false
    default: 1 # Pulled from actions/checkout docs
  git-fetch-tags:
    type: boolean
    required: false
    default: false

runs:
  using: composite
  steps:
  - uses: actions/checkout@v3
    with:
      ref: ${{ inputs.git-ref }}
      fetch-depth: ${{ inputs.git-fetch-depth }}
      fetch-tags: ${{ inputs.git-fetch-tags }}
      show-progress: false
  - uses: actions/setup-node@v3
    with:
      node-version: ${{ inputs.node-version }}
      cache: yarn
    env:
      FORCE_COLOR: 0
