name: Bootstrap Action

inputs:
  node-version:
    type: string
    required: false
    default: lts/iron
  git-ref:
    type: string
    required: false
    default: ''
  git-fetch-depth:
    type: number
    required: false
    default: 1 # Pulled from actions/checkout docs
  git-fetch-tags:
    type: boolean
    required: false
    default: false

runs:
  using: composite
  steps:
  - uses: actions/checkout@v4
    with:
      ref: ${{ inputs.git-ref }}
      fetch-depth: ${{ inputs.git-fetch-depth }}
      fetch-tags: ${{ inputs.git-fetch-tags }}
      show-progress: false
  - id: node_version
    name: Resolve node version
    shell: bash
    run: |
      if [[ "$NODE_VERSION" == "package_json" ]]; then
        echo "value=$(jq -r .engines.node package.json)" >> $GITHUB_OUTPUT
      else
        echo "value=$NODE_VERSION" >> $GITHUB_OUTPUT
      fi
    env:
      NODE_VERSION: ${{ inputs.node-version }}
  - uses: actions/setup-node@v4
    with:
      node-version: ${{ steps.node_version.outputs.value }}
      cache: yarn
    env:
      FORCE_COLOR: 0
